version: '3.8'

services:

  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3001:3000"
    depends_on:
      - postgres
    links:
      - postgres

  postgres:
    image: postgres:15.4
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=root
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "root", "-U", "root"]
      interval: 5s
      timeout: 10s
      retries: 5
    volumes:
      - server-data:/var/lib/pgsql/data

  pgadmin: 
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "80:80"
    depends_on:
      - postgres
  
volumes:
  server-data: