version: '3.8'

services:

  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  postgres:
    image: postgres:15.4
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=root
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "root", "-U", "root"]
      interval: 5s
      timeout: 10s
      retries: 5

  pgadmin: 
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "80:80"
    depends_on:
      - postgres